### ISSUE TITLE
build issues to be addressed

### ISSUE THREAD

**Issue by cl1337** [uber/zanzibar#421] opened 2018-08-01 00:55 UTC
open this issue to record bugs related to build / codegen

1: [] `http.ref` fail requireness check
when tag field with `http.ref` :   `1: required string fieldA (http.ref="params.key")`, it means the value of this field is required from url `localhost:<port>/path/to/endpoint?key=value`, instead of request body, but our unmarlshal isn't handling this case

2: [] query params could be typedef 
```
typedef string uuid

struct A {
    1: required uuid field (http.ref="query.key")
}
```
we can only assign string from query params to A.uuid, which will cause build fail

**Comment by ChuntaoLu** [comment] 2018-08-14 23:57
> 1: [] http.ref fail requireness check
when tag field with http.ref : 1: required string fieldA (http.ref="params.key"), it means the value of this field is required from url localhost:<port>/path/to/endpoint?key=value, instead of request body, but our unmarshal isn't handling this case

`1: required string fieldA (http.ref="params.key")` means params in the url not query params, i.e. the value is required from `localhost:<port>/:key/path/to/endpoint` and it's present as long as the url is matched to the registered url. The part `?key=value` is query params not params.

> 2: [] query params could be typedef

This is a duplicate of https://github.com/uber/zanzibar/issues/415

**Closed by ChuntaoLu** 2018-08-14 23:57 UTC
Labels: bug
